
import time
import random
from pynput.keyboard import Key, Controller

keyboard = Controller()  # Create the controller

keyboard.press(Keycode.CONTROL)
keyboard.press(Keycode.ALT)
keyboard.press(Keycode.T)
keyboard.release(Keycode.CONTROL)
keyboard.release(Keycode.ALT)
keyboard.release(Keycode.T)
time.sleep(1)
keyboard.type("cd lovebits\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
time.sleep(1)
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.type("python main.py\n")
keyboard.press(Keycode.CONTROL)
keyboard.press(Keycode.ALT)
keyboard.press(Keycode.D)
keyboard.release(Keycode.CONTROL)
keyboard.release(Keycode.ALT)
keyboard.release(Keycode.D)

